### ISSUE TITLE
Сделать мок списка и обзора выпускников (было: Проблема с учениками)

### ISSUE THREAD

**Issue by Nonobisha** [TLVL/TLVL-alumni#2]
Список не работает как должен.

**Comment by Nonobisha** [comment]
![image](https://user-images.githubusercontent.com/51201058/59145301-81876f00-89ea-11e9-937d-4940b2ac02d3.png)

**Comment by dfisun** [comment]
Пока предлагаю сделать статичный список, чтобы оценить идею визуально.

**Comment by Nonobisha** [comment]
Сделал статичным

**Comment by dfisun** [comment]
В списке поставить что-то, похожее на имена людей. Справа поставить инфо о выбранном выпускнике.

**Comment by dfisun** [comment]
Вопрос неактуален
