### ISSUE TITLE
Создать страницу приветствия

### ISSUE THREAD

**Issue by dfisun** [TLVL/TLVL-alumni#5]
Логотип Лицея по центру страницы, под ним текст:

> Дорогие лицеисты! Совсем скоро здесь откроется карта выпускников (**примерно такая**). Чтобы не пропустить этот момент, **поставьте эту страницу в закладки** и подпишитесь на обновления:

Ниже поставить гугл-форму.

Ссылка `примерно такая` ведет на `/mock`
Ссылка `поставьте эту страницу в закладки` добавляет страницу в закладки

**Comment by dfisun** [comment]
NB! Это не мок, создать её как основную страницу Express.

**Comment by Nonobisha** [comment]
Сделано.

**Comment by dfisun** [comment]
Добавить гугл-форму или уже поставить собственную

**Comment by dfisun** [comment]
Задача неактуальна.
